language: python
sudo: false
cache: pip
matrix:
  include:
    - python: 3.6
    - arch: arm64
      python: 3.6
    - python: 3.7
      dist: xenial
    - python: 3.7
      arch: arm64
      dist: xenail
install:
  - pip install 'pytest>=3.6' pytest-cov codecov pydocstyle pycodestyle numpy==1.16
  - python setup.py install
# command to run tests
script:
  - pytest --cov=response tests

after_success:
  - git config --global user.name "semantic-release (via TravisCI)"
  - git config --global user.email "semantic-release@travis"
  - pip install python-semantic-release
  - semantic-release --post publish
  - codecov
branches:
  only:
    - master

